# site settings
title: My journey with Data
subtitle: by Baraa Zaghmout
email: b.zaghmout@outlook.com
description: My personal journey in data science.
baseurl: "/Blog/" # the subpath of your site, e.g. /blog
url: "https://BaraaZaghmout.github.io" # the base hostname & protocol for your site
#author: Baraa Zaghmout
#street_address: 1234 Somewhere Road
#city: Nashville
#state: TN
#zip_code: 55555
#country: United States of America
#phone: (716) 555-5555

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
github_url: https://github.com/BaraaZaghmout
#gitlab_url: https://gitlab.com/u/andrewbanchich
linkedin_url: https://www.linkedin.com/in/baraa-zaghmout
#slack_url:

# build settings
markdown: kramdown

sass:
  style: compressed
