# site settings
title: My journey with Data
subtitle: by Baraa Zaghmout
email: b.zaghmout@outlook.com
description: My personal journey in data science.
baseurl: "/Blog" # the subpath of your site, e.g. /blog
url: "https://BaraaZaghmout.github.io" # the base hostname & protocol for your site
author: Baraa Zaghmout
street_address: Bremerstrasse 23
city: Kiel
state: Schleswig Holstein
zip_code: 24118
country: Germany
phone: (+49) 157 57294843

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
github_url: https://github.com/BaraaZaghmout
linkedin_url: https://www.linkedin.com/in/baraa-zaghmout

# build settings
markdown: kramdown

sass:
  style: compressed
